#!/usr/bin/lua

local json=require("jsonc")
local f = assert(io.popen("ip -6 -br -j addr show dev br-client scope link", 'r'))
local s = assert(f:read('*a'))                                                    
f:close()                                                                         
local ll = json.parse(s)[1]["addr_info"][2]["local"]

local f = io.open("/tmp/range6","r")

if f then
    local range6 = f:read('*a')
    f:close()

    io.write("-i br-client -p " .. range6)
    io.write(" --rdnss " .. ll)
end
