#!/usr/bin/lua

local f = io.open("/tmp/range6","r")
if f then
    local range6 = f:read('*a')
    f:close()

    io.write("-i br-client -p " .. range6)
end

local f = io.open("/tmp/addr6","r")
if f then
    local addr6 = f:read('*a')
    f:close()

    io.write(" --rdnss " .. addr6)
end
if site.radvd() then
	if site.radvd.preferred_lifetime() then
		io.write(" --preferred-lifetime " .. site.radvd.preferred_lifetime())
	end
	if site.radvd.valid_lifetime() then
		io.write(" --valid-lifetime " .. site.radvd.valid_lifetime())
	end
end
