#!/usr/bin/lua

local site = require "gluon.site"

local f = io.open("/tmp/range6","r")
if f then
    local range6 = f:read('*a')
    f:close()
    io.write("-i br-client -p " .. range6)

    if site.dns.servers() and site.next_node.ip6() then
        io.write(" --rdnss " .. site.next_node.ip6())
    end
end
