#!/usr/bin/lua

local uci = require('simple-uci').cursor()

local vpn_config = {
	enabled = uci:get_bool('gluon', 'mesh_vpn', 'enabled'),
	limit_enabled = uci:get_bool('gluon', 'mesh_vpn', 'limit_enabled'),
	limit_egress = uci:get('gluon', 'mesh_vpn', 'limit_egress'),
	limit_ingress = uci:get('gluon', 'mesh_vpn', 'limit_ingress'),
}

uci:delete('simple-tc', 'client')
uci:section('simple-tc', 'interface', 'client', {
	ifname = 'br-client',
	enabled = vpn_config.limit_enabled,
	-- limits are flipped here
	limit_ingress = vpn_config.limit_egress,
	limit_egress = vpn_config.limit_ingress,
})
uci:commit('simple-tc')
